import type { AppProps } from "next/app";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import "../styles/globals.css";

const pathNames = [
  "/data-display",
  "/data-input",
  "/layout",
  "/navigation",
  "/mockup",
];

const links = ["Data Display", "Data Input", "Layout", "Navigation", "Mockup"];

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Tailwind + daisyUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-evenly">
        {pathNames.map((path, i) => (
          <li key={path} className={path === router.asPath ? "active" : ""}>
            <Link href={path}>{links[i]}</Link>
          </li>
        ))}
      </nav>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
